services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    restart: "unless-stopped"
    networks:
      - jarvis-plugin-network
    env_file:
      - ./nginx/.env
    entrypoint: >
      /bin/bash -c "printenv && envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - jarvis-helpdesk-ai-module
      - certbot
  jarvis-helpdesk-ai-module:
    build:
      context: ./jarvis-helpdesk-ai-module
      dockerfile: Dockerfile
    restart: "unless-stopped"
    env_file:
      - ./jarvis-helpdesk-ai-module/.env
    ports:
      - "5501:5502"
    expose:
      - 5502
    networks:
      - jarvis-plugin-network
  certbot:
    image: certbot/certbot
    container_name: certbot_ai_module
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email hiiback0608@gmail.com -d jarvis-admin.shop --agree-tos
networks:
  jarvis-plugin-network:
    driver: bridge